
name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Requirements
      run: sudo apt-get install -y clang-11 libc++-11-dev libc++abi-11-dev libsodium-dev libcurl4-openssl-dev
      
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.REPO_ACCESS }}
        submodules: recursive
    - name: Build
      run: |
        export CC=clang-11
        export CXX=clang++-11
        mkdir -p build && pushd build
        cmake ..
        make cxx_depends_all
        popd
